# Generated by Django 5.2 on 2025-05-04 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=10, help_text='사용자가 가진 크레딧 수'),
        ),
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='사용하거나 충전한 크레딧 양')),
                ('is_usage', models.BooleanField(default=True, help_text='사용인지 충전인지 여부 (True: 사용, False: 충전)')),
                ('reason', models.CharField(help_text='크레딧 변동 이유', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '크레딧 사용 내역',
                'verbose_name_plural': '크레딧 사용 내역',
                'ordering': ['-created_at'],
            },
        ),
    ]
