# Generated by Django 5.2 on 2025-05-04 10:48

import ai_image_converter.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_converter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonimage',
            name='converted_image',
            field=models.ImageField(blank=True, help_text='만화 스타일로 변환된 이미지', null=True, upload_to=ai_image_converter.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='cartoonimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='변환 요청이 생성된 시간'),
        ),
        migrations.AlterField(
            model_name='cartoonimage',
            name='model_used',
            field=models.CharField(default='default_model', help_text='변환에 사용된 AI 모델 (예: default_model, anime_style, pixel_art, cartoon_realistic)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartoonimage',
            name='original_image',
            field=models.ImageField(help_text='변환할 원본 이미지', upload_to=ai_image_converter.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='cartoonimage',
            name='prompt',
            field=models.TextField(blank=True, help_text="이미지 변환을 위한 추가 지시사항 (예: '스튜디오 지브리 스타일로 변환해주세요')", null=True),
        ),
        migrations.AlterField(
            model_name='cartoonimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='현재 변환 상태 (pending: 대기 중, processing: 처리 중, completed: 완료, failed: 실패)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartoonimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='마지막으로 변환 상태가 업데이트된 시간'),
        ),
        migrations.AlterField(
            model_name='cartoonimage',
            name='user',
            field=models.ForeignKey(help_text='이미지를 업로드한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='cartoon_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
