# Generated by Django 5.2 on 2025-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_converter', '0003_rename_cartoon_to_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimage',
            name='error_message',
            field=models.TextField(blank=True, help_text='변환 실패 시 에러 메시지', null=True),
        ),
    ]
